version: "3.2"

services:

  test-library:
    build: .
    environment:
      TEST: 'true'
      # emulator instance
      FIRESTORE_EMULATOR_HOST: emulator:8080
      FIREBASE_DATABASE_EMULATOR_HOST: emulator:9000
      # connect to real instance (optional)
      # FIREBASE_HOST: ${FIREBASE_HOST-}
      # FIREBASE_CREDENTIALS: ${FIREBASE_CREDENTIALS-}
      # FIREBASE_PROJECT_ID: ${FIREBASE_PROJECT_ID-}
      LOGIAK_APP_ID: 4f5f6d96-62fd-4e1d-a6ba-2bfb37d0d0db # the demo app (LoMIS) in emulator
      WEB_API_KEY: ${WEB_API_KEY-}
    ports:
      - 9009:9009
    entrypoint:
      "/test/entrypoint.sh"
    command:
      "start"

  emulator:
    image: ehealthafrica/firebase-emulator:latest
    volumes:
      # - ./hosted.json:/app/override.json:rw
      # - firebase:/app/fb/functions:rw
      # - firebase:/app/fb/public:rw
      - firebase:/home/docker/.cache/firebase/emulators:rw
      - firebase:/app/fb:rw
    environment:
      FIREBASE_TOKEN: ${FIREBASE_TOKEN-}
      FIREBASE_PROJECT: ${FIREBASE_PROJECT-}
    ports:
      - 5001:5001
      - 9000:9000
      - 8080:8080
      - 8085:8085
      - 5000:5000
      - 4000:4000
    entrypoint:
      ["/app/entrypoint.sh", "run_basic"]

volumes:
  firebase:
    driver: local
    driver_opts:
      type: volume
      o: bind
      device: "${PWD}/data"
